[package]
name = "spora-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
spora-core = { path = "../spora-core" }
clap = { version = "4.5.52", features = ["derive"] }
tokio = "1.48.0"
env_logger = "0.11.8"
futures-util = "0.3.31"
log = "0.4.29"
url = "2.5.7"

[target.'cfg(not(windows))'.dependencies]
tokio-tun = "0.12.1"
tikv-jemallocator = "0.6"