//! Resolver handling shared by the Unix backends: the `resolv.conf`
//! replace-in-place tier (Linux's last resort) and its crash-recovery rules.
//!
//! `resolv.conf` is rewritten in place rather than renamed over: it is often
//! a symlink into `/run` (systemd-resolved) or a bind mount (containers, the
//! lab), and a rename would replace the link itself. The original goes to a
//! backup file next to it and the generated file carries a marker line, so a
//! later start can tell "our file after a crash" from "someone else's file"
//! and restore accordingly.

use std::io;
use std::net::IpAddr;
use std::path::Path;

use super::Undo;

pub const RESOLV_CONF: &str = "/etc/resolv.conf";
/// Where the original goes while we run, in preference order: next to the
/// file, or — when `/etc` itself is not writable (immutable distros,
/// namespaced containers where only resolv.conf is a writable mount) —
/// under `/run`. Recovery checks every candidate.
pub const RESOLV_BACKUPS: [&str; 2] = [
    "/etc/resolv.conf.spora-backup",
    "/run/spora/resolv.conf.spora-backup",
];
/// First line of every resolv.conf this tool writes.
pub const MARKER: &str = "# Generated by spora use";

/// Build the replacement resolv.conf: our resolvers, plus the original's
/// `search`/`domain`/`options`/`sortlist` directives (local suffixes keep
/// working; only *where* queries go changes).
pub fn render_resolv_conf(original: &str, servers: &[IpAddr], backup: &Path) -> String {
    let mut out = String::new();
    out.push_str(MARKER);
    out.push('\n');
    out.push_str(&format!(
        "# The previous file is saved at {} and restored when spora exits.\n",
        backup.display()
    ));
    for s in servers {
        out.push_str(&format!("nameserver {s}\n"));
    }
    for line in original.lines() {
        let t = line.trim_start();
        if t.starts_with("search ")
            || t.starts_with("domain ")
            || t.starts_with("options ")
            || t.starts_with("sortlist ")
        {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

pub fn is_spora_generated(text: &str) -> bool {
    text.lines().next().is_some_and(|l| l.trim() == MARKER)
}

/// Crash recovery, run before touching the resolver: a backup left behind by
/// an earlier run is put back if `resolv` still holds our generated file;
/// if something else has rewritten `resolv` since, the backup is stale and is
/// discarded. Returns whether a restore happened.
pub fn restore_stale_backup(resolv: &Path, backup: &Path) -> io::Result<bool> {
    let Ok(saved) = std::fs::read_to_string(backup) else {
        return Ok(false);
    };
    let current = std::fs::read_to_string(resolv).unwrap_or_default();
    let restored = if is_spora_generated(&current) {
        std::fs::write(resolv, saved)?;
        true
    } else {
        false
    };
    std::fs::remove_file(backup)?;
    Ok(restored)
}

/// Replace `resolv` in place with our resolvers, saving the original to the
/// first of `backups` that can be written. The returned undo puts the
/// original back (in place) and removes the backup.
pub fn replace_resolv_conf(
    resolv: &Path,
    backups: &[&Path],
    servers: &[IpAddr],
) -> io::Result<Undo> {
    let original = match std::fs::read_to_string(resolv) {
        Ok(s) => Some(s),
        Err(e) if e.kind() == io::ErrorKind::NotFound => None,
        Err(e) => return Err(e),
    };
    let mut backup = None;
    let mut last_err = io::Error::other("no backup path candidates");
    for candidate in backups {
        if let Some(dir) = candidate.parent()
            && let Err(e) = std::fs::create_dir_all(dir)
        {
            last_err = e;
            continue;
        }
        match std::fs::write(candidate, original.as_deref().unwrap_or("")) {
            Ok(()) => {
                backup = Some(candidate.to_path_buf());
                break;
            }
            Err(e) => last_err = e,
        }
    }
    let Some(backup) = backup else {
        return Err(last_err);
    };
    let was_symlink = std::fs::symlink_metadata(resolv)
        .map(|m| m.file_type().is_symlink())
        .unwrap_or(false);
    std::fs::write(
        resolv,
        render_resolv_conf(original.as_deref().unwrap_or(""), servers, &backup),
    )?;
    // When the file did not exist, undo must remove what the write created.
    // Through a dangling symlink that is the TARGET — unlinking `resolv`
    // itself would destroy the host's symlink arrangement.
    let created = match (&original, was_symlink) {
        (Some(_), _) => None,
        (None, false) => Some(resolv.to_path_buf()),
        (None, true) => std::fs::canonicalize(resolv).ok(),
    };
    let resolv = resolv.to_path_buf();
    Ok(Undo::Fn(Box::new(move || {
        let res = match &original {
            Some(text) => std::fs::write(&resolv, text),
            None => match &created {
                Some(path) => std::fs::remove_file(path),
                None => Ok(()),
            },
        };
        if let Err(e) = res {
            log::warn!("cleanup: restoring {} failed: {}", resolv.display(), e);
        }
        let _ = std::fs::remove_file(&backup);
    })))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> std::path::PathBuf {
        let d = std::env::temp_dir().join(format!("spora-vpn-dns-{}-{}", tag, std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    fn servers() -> Vec<IpAddr> {
        vec![
            "8.8.8.8".parse().unwrap(),
            "2606:4700::1111".parse().unwrap(),
        ]
    }

    #[test]
    fn rendered_file_keeps_search_and_options_but_not_old_nameservers() {
        let original = "# Generated by NetworkManager\nsearch lan home\nnameserver 192.168.1.1\noptions edns0 trust-ad\n";
        let text = render_resolv_conf(original, &servers(), Path::new("/etc/x.bak"));
        assert!(is_spora_generated(&text));
        assert!(text.contains("nameserver 8.8.8.8\n"));
        assert!(text.contains("nameserver 2606:4700::1111\n"));
        assert!(text.contains("search lan home\n"));
        assert!(text.contains("options edns0 trust-ad\n"));
        assert!(!text.contains("192.168.1.1"));
        assert!(text.contains("/etc/x.bak"));
    }

    #[test]
    fn replace_then_undo_round_trips_in_place() {
        let d = scratch("roundtrip");
        let resolv = d.join("resolv.conf");
        let backup = d.join("resolv.conf.bak");
        std::fs::write(&resolv, "nameserver 10.0.0.1\nsearch corp\n").unwrap();
        let undo = replace_resolv_conf(&resolv, &[&backup], &servers()).unwrap();
        let now = std::fs::read_to_string(&resolv).unwrap();
        assert!(is_spora_generated(&now));
        assert!(now.contains("search corp"));
        assert_eq!(
            std::fs::read_to_string(&backup).unwrap(),
            "nameserver 10.0.0.1\nsearch corp\n"
        );
        match undo {
            Undo::Fn(f) => f(),
            _ => panic!("expected a closure undo"),
        }
        assert_eq!(
            std::fs::read_to_string(&resolv).unwrap(),
            "nameserver 10.0.0.1\nsearch corp\n"
        );
        assert!(!backup.exists());
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn missing_resolv_conf_is_created_and_removed_again() {
        let d = scratch("missing");
        let resolv = d.join("resolv.conf");
        let backup = d.join("resolv.conf.bak");
        let undo = replace_resolv_conf(&resolv, &[&backup], &servers()).unwrap();
        assert!(resolv.exists());
        match undo {
            Undo::Fn(f) => f(),
            _ => panic!(),
        }
        assert!(!resolv.exists());
        assert!(!backup.exists());
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn backup_falls_through_to_a_writable_location() {
        use std::os::unix::fs::PermissionsExt as _;
        let d = scratch("fallback");
        let resolv = d.join("resolv.conf");
        std::fs::write(&resolv, "nameserver 10.0.0.1\n").unwrap();
        let locked = d.join("locked");
        std::fs::create_dir(&locked).unwrap();
        std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o555)).unwrap();
        let primary = locked.join("resolv.conf.bak");
        let fallback = d.join("writable").join("resolv.conf.bak");
        let undo = replace_resolv_conf(&resolv, &[&primary, &fallback], &servers()).unwrap();
        assert!(!primary.exists());
        assert_eq!(
            std::fs::read_to_string(&fallback).unwrap(),
            "nameserver 10.0.0.1\n"
        );
        let text = std::fs::read_to_string(&resolv).unwrap();
        assert!(
            text.contains(&fallback.display().to_string()),
            "marker names the real backup: {text}"
        );
        match undo {
            Undo::Fn(f) => f(),
            _ => panic!(),
        }
        assert_eq!(
            std::fs::read_to_string(&resolv).unwrap(),
            "nameserver 10.0.0.1\n"
        );
        assert!(!fallback.exists());
        std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o755)).unwrap();
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn dangling_symlink_resolv_conf_survives_the_round_trip() {
        let d = scratch("symlink");
        std::fs::create_dir_all(d.join("run")).unwrap();
        let resolv = d.join("resolv.conf");
        let target = d.join("run").join("target.conf");
        std::os::unix::fs::symlink(&target, &resolv).unwrap();
        let backup = d.join("resolv.conf.bak");
        let undo = replace_resolv_conf(&resolv, &[&backup], &servers()).unwrap();
        assert!(target.is_file(), "write went through the symlink");
        assert!(is_spora_generated(
            &std::fs::read_to_string(&resolv).unwrap()
        ));
        match undo {
            Undo::Fn(f) => f(),
            _ => panic!(),
        }
        assert!(
            std::fs::symlink_metadata(&resolv)
                .unwrap()
                .file_type()
                .is_symlink(),
            "the symlink itself must survive cleanup"
        );
        assert!(!target.exists(), "the created target is removed");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn stale_backup_restores_only_over_our_own_file() {
        let d = scratch("stale");
        let resolv = d.join("resolv.conf");
        let backup = d.join("resolv.conf.bak");
        // Nothing to do without a backup.
        assert!(!restore_stale_backup(&resolv, &backup).unwrap());
        // Crash left our file + backup behind: restore.
        std::fs::write(&backup, "nameserver 10.0.0.1\n").unwrap();
        std::fs::write(&resolv, render_resolv_conf("", &servers(), &backup)).unwrap();
        assert!(restore_stale_backup(&resolv, &backup).unwrap());
        assert_eq!(
            std::fs::read_to_string(&resolv).unwrap(),
            "nameserver 10.0.0.1\n"
        );
        assert!(!backup.exists());
        // Crash, then NetworkManager rewrote resolv.conf: the backup is stale
        // and must NOT clobber the newer file.
        std::fs::write(&backup, "nameserver 10.0.0.1\n").unwrap();
        std::fs::write(&resolv, "nameserver 172.16.0.1\n").unwrap();
        assert!(!restore_stale_backup(&resolv, &backup).unwrap());
        assert_eq!(
            std::fs::read_to_string(&resolv).unwrap(),
            "nameserver 172.16.0.1\n"
        );
        assert!(!backup.exists());
        let _ = std::fs::remove_dir_all(&d);
    }
}
